import type { Metadata } from "next";
import { Geist, Geist_Mono, Work_Sans } from "next/font/google";
import "./globals.css";
import {Room} from '../app/Room'


const workSans =  Work_Sans ({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ['400','600','700'],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ workSans.variable} bg-primary-grey-200 ${geistMono.variable} antialiased`}
      >
        <Room>
        {children}

        </Room>
       
      </body>
    </html>
  );
}
